/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zell_jnative_BucketBufferArray */

#ifndef _Included_de_zell_jnative_BucketBufferArray
#define _Included_de_zell_jnative_BucketBufferArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zell_jnative_BucketBufferArray
 * Method:    allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zell_jnative_BucketBufferArray_allocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zell_jnative_BucketBufferArray
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zell_jnative_BucketBufferArray_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
